## Assignment-14&15

In [1]:
import numpy as np


# 1. Create a 3x3x3 array with random values 

In [2]:
a=np.random.rand(3,3,3)
a

array([[[0.60011975, 0.07020031, 0.4198477 ],
        [0.91353365, 0.83169888, 0.47353002],
        [0.85418878, 0.02930028, 0.26429126]],

       [[0.92436956, 0.04211318, 0.61176805],
        [0.52626696, 0.92076776, 0.38410122],
        [0.76125183, 0.39564088, 0.24633939]],

       [[0.10106396, 0.64958095, 0.98560675],
        [0.64999364, 0.61441848, 0.59698616],
        [0.41067458, 0.41077552, 0.91722787]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
b=np.zeros((5,5))
for i in range(4):
    b[i+1,i]=i+1
b

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
c=np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if((i%2==0) and (j%2!=0)):
            c[i,j]=1
        elif((i%2!=0) and (j%2==0)):
            c[i,j]=1
print("checkerboard pattern : \n",c)

checkerboard pattern : 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [5]:
d=np.random.randn(5,5)
d

array([[ 1.29268618,  0.84687906,  0.67489266,  1.82128407,  0.03728374],
       [-1.01587928, -0.50207644, -0.84199799,  0.07224691,  0.30017659],
       [ 0.01113232,  0.57718454,  1.20629784, -1.32146761,  1.15514347],
       [ 0.7693827 , -0.87402616, -0.46951162, -0.2516051 ,  1.60695333],
       [ 1.28307183,  2.19126849,  0.23468856, -0.41529806, -0.87247995]])

# 5.  How to find common values between two arrays?

In [6]:
a=np.array([1,3,5,6,7,7,5,7,4])
b=np.array([3,6,7,11,3,7,9,8,0,3])
c=[]
for i in set(a):
    for j in set(b):
        if (i==j):
            c.append(i)

print("the common values between a and b arrays : ",c)

the common values between a and b arrays :  [3, 6, 7]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64("today") - np.timedelta64(1)
today = np.datetime64("today")
tomorrow = np.datetime64("today") + np.timedelta64(1)
print("yesterday date: ",yesterday)
print("today date    : ",today)
print("tomorrow date : ",tomorrow)


yesterday date:  2020-07-27
today date    :  2020-07-28
tomorrow date :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [8]:
a=np.random.rand(5,5)
b=np.random.rand(5,5)
if ((a==b).all()):
    print("a and b are equal")
else:
    print("a and b are not equal")

a and b are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
a=np.random.random(10)
print(a)

[0.69478681 0.33948334 0.51396777 0.16804868 0.95505274 0.37418649
 0.25871159 0.86043628 0.77467082 0.82299974]


In [10]:
b=np.sort(a)
b[-1]=0
b

array([0.16804868, 0.25871159, 0.33948334, 0.37418649, 0.51396777,
       0.69478681, 0.77467082, 0.82299974, 0.86043628, 0.        ])

# 9. How to print all the values of an array?

In [11]:
a=np.array([1,2,2,3,4,11])
for i in a:
    print(i,end=" ")

1 2 2 3 4 11 

# 10.Subtract the mean of each row of a matrix

In [12]:
b=np.array([[1,2],[3,4],[6,8]])
b=b-np.mean(b,axis=1,keepdims=True)
b

array([[-0.5,  0.5],
       [-0.5,  0.5],
       [-1. ,  1. ]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [13]:
a=np.array([21,12,13,7,11,7,19,10,24])
b=np.array([2,4,6,9,1,11])
for j in set(b):
    if j<len(a):
        a[j]=1
print("new array: ",a)
        

new array:  [21  1  1  7  1  7  1 10 24]


# 12.How to get the diagonal of a dot product?

In [14]:
X= np.array([[1,2,3],[2,4,3]])
Y=np.array([[1,2],[3,5],[7,6]])
diag= np.diag(X.dot(Y))
print("diag: ",diag)

diag:  [28 42]


# 13.How to find the most frequent value in an array?

In [15]:
d={}
a=np.array([2,8,9,5,6,7,6,4,8,9,9,9,7,7,0])
for i in set(a):
    c=0;
    for j in a:
        if(i==j):
            c=c+1
    d[i]=c

f=np.array((list(d.values())))
g=np.max(f)

f1=[]
for k in d.keys():
    if(d[k]== g):
        f1.append(k)

print("the most frequent value in the array: ",f1)

the most frequent value in the array:  [9]


# 14.How to get the n largest values of an array

In [16]:
a=np.array([5,8,3,6,0,2,1,15,7,5,11])

In [17]:
n=int(input("enter the number n: "))
print(f"the {n} largest values of the array {a}  : ",np.sort(a)[-1:-(n+1):-1])

enter the number n: 4
the 4 largest values of the array [ 5  8  3  6  0  2  1 15  7  5 11]  :  [15 11  8  7]


# 15.How to create a record array from a regular array?

In [18]:
a=np.array([("ram",78,88),("priya",77,97),("geeta",88,89)])
print("regular array: ",a)

regular array:  [['ram' '78' '88']
 ['priya' '77' '97']
 ['geeta' '88' '89']]


In [19]:
rec=np.core.records.fromarrays(a.T,names='col1, col2, col3',formats = 'S80, f8, i8')
print("record array: ",rec)

record array:  [(b'ram', 78., 88) (b'priya', 77., 97) (b'geeta', 88., 89)]
